### PR TITLE
Fix build workflow

### LINKED ISSUE #231: update ci to use newer version of macos

### LINKED ISSUE #346: Can't clone repo on Windows
The docs have files with a `:` colon in the filename (i.e. `About:-Bsc-plugin.md`)and because of this the repo can't be cloned on Windows computers.

maestro-clone-error

### PR DESCRIPTION
**Pull request by cewert**
## Changes
- Use latest versions of ubuntu and macos (this is why the ci was failing. the versions listed are deprecated - see [here](https://github.com/georgejecook/maestro-roku/actions/runs/4957199651))
- Use latest LTS version of node and cache NPM dependencies - currently that is v18.16.0 (see [here](https://github.com/georgejecook/maestro-roku/actions/runs/4984632549/jobs/8923220479?pr=377#step:3:12))
- Re-enable `npm run lint` 
- Also updates the `npm-release` job to use the latest versions of ubuntu, macos, and node
- Re-add windows to os matrix
- Use latest version of windows os
- Remove colons from all filenames (this is why the windows build was failing)
- Update doc links - remove colons from filenames
- Update separator in `options.json` to `--` and update all doc files to match

Fixes #346
Fixes #231

### CODE REVIEW

**Comment by cewert** [comment]
I just stumbled on to `options.json` which still had the colons in the filename. I also noticed this file had a "separator" field set to `:-`. I changed the separator value to `--` and renamed the doc files to match. I'm not sure what the options.json file does but I know removing the colons without updating the searator would have broken it so I did my best to fix it.

PS: I noticed some of the doc files were missing from the `options.json` file (`List-Component--*`). I'll leave that for you since I don't know what order you want them or how to even test my changes.

**Comment by georgejecook** [comment]
hey @cewert, I missed this I'm afraid, and updated this project to use release-it, so there's a bunch of merge conflicts. I just resolved them locally, but can't push to your branch. If you get this synced with main, I'll be happy to accept the pr.
It would only take a few minutes to merge - we no longer do releases via github.. so you'll observe the build.yml no loner has the release stuff and npm packaging in it.

**Comment by cewert** [comment]
I'm not sure why you can't push to my branch. I don't think I enabled branch protections or anything 🤷 

I'll try to look at this today sometime

**Comment by georgejecook** [comment]
thanks!

**Pull request merged**
